### ISSUE TITLE
Backend Funcionalidad de Pagos

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#10]
Backend Funcionalidad de Pagos

Objetivos:

**TODO**
**DOING**

**DONE**

- [x] Retornar la lista de usuarios, para poder hacer transferencias internas (excluyendo a uno mismo)
- [x]  Que haya un movimiento inicial para que los usuarios tengan mas saldo. ($ 20.000) +- 30%
Implementado
- [x]  Hacer el crédito a una cuenta
- [x]  Soportar la cotización del dólar ... algún servicio cloud o API externo

**Comment by Pabloin** [comment]
- [ ] Compras por rubro de Tarjetas

**TODO:**

- [ ] Que el backend devuelva un discrecional de movimientos
