### ISSUE TITLE
Tu! Backend - Fixes Varios (II)

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#14]
Tu! Backend - Fixes Varios (II)

**TODO**

**DOING**

**DONE**

- [x] Servicio del dólar desde el backend
- [x] FIX Error de límite de 100 accesos por día

**Comment by Pabloin** [comment]
- [x] FIX Error de límite de 100 accesos por día

![image](https://user-images.githubusercontent.com/21208987/64457163-4ae3f200-d0c8-11e9-99f3-5542b3fe3cfd.png)
