### ISSUE TITLE
Tu! Backend End - Compras

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#15]
Tu! Backend End - Compras

- [x] Compras por rubro de Tarjetas

**TODO:**

- [x] Que el backend devuelva un discrecional de movimientos

**Comment by Pabloin** [comment]
- [x] Que el backend devuelva un discrecional de movimientos

![image](https://user-images.githubusercontent.com/21208987/64543036-e9579980-d2fa-11e9-9a48-b9bbc704f853.png)
