### ISSUE TITLE
Medio de Persistencia

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#2]
Medio de Persistencia

**TODO**

**DOING**

**DONE**

- [x] persisto en mongodb los saldos y movimientos
- [x] API REST en el Backend que impacte al medio de persistencia
- [x] Duda: ¿Puedo hacer las cosas de un saque? IE Backend nodejs + MongoDB
