### ISSUE TITLE
Backend API REST

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#3]
- [x] API REST en el Backend que impacte al medio de persistencia

**TODO**

**DOING**

**DONE**

- [x] Evaluar 3 Scale -> Voy por "SwaggerHub"
- [x] Exponer las API REST 's  Users/TransactionID/Accounts
- [x] PoC  "SwaggerHub"

**DISCARTED**

- [x] PoC Loopback con OpenAPI3
