### ISSUE TITLE
Login User Backend

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#4]
Login User Backend

**TODO** 

**DOING** 

**DONE**

- [x] (T1) Tener la API "Insegura/abierta" cargada en el Postman
- [x] App v2 a la raiz 
- [x] .env compatible
- [x] (t3) Unificar las dos APPS // APIś
- [x] (t4) Implementar POST `/sessions/create`
