### ISSUE TITLE
Swagger Online API (Browse/editor)

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#5]
Swagger Online API (Browse/editor)

**TODO**

- [x] Swagger Edittor en el Server Side ante /GET

**DONE**

- [x] Swagger Edittor local con Docker

### Objetivo:

Habilitar el editor online para la API

![image](https://user-images.githubusercontent.com/21208987/63607526-112fc900-c5a9-11e9-8aeb-81f038ccd050.png)

v1: Después de Importar el YAML

![image](https://user-images.githubusercontent.com/21208987/63608187-bbf4b700-c5aa-11e9-8116-44dd35660a2a.png)

**Comment by Pabloin** [comment]
- [ ] Swagger Edittor en el Server Side ante /GET

OBJETIVO:
De acuerdo a 
- https://swagger.io/docs/open-source-tools/swagger-editor/
- https://github.com/swagger-api/swagger-editor
y especialmente a:
- https://www.npmjs.com/package/swagger-editor-dist

Se puede agregar el swagger editor como un /dist en el proyecto del lado del server side
Vamos a agreagrlos para que cuando le pegue a /GET tenga la API a disposición

**Comment by Pabloin** [comment]
Primero:

- [ ] Instalo con
 npm i --save swagger-editor-dist

- [ ] Publico con GET

**Comment by Pabloin** [comment]
Ok: Swagger on local with:

![image](https://user-images.githubusercontent.com/21208987/64085497-8c138500-cd09-11e9-8b1b-a9b5660d0410.png)
