### ISSUE TITLE
Agregar campo email usuario

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/techu-backend#6]
Agregar campo email usuario

**TODO**

- [x] Probar un alta

**DOING**

**DONE**

- [x] En el Front, el formulario de login debe tener el mail
- [x] En la base de datos, agregar el email a todos
- [x] Swagger la definicion
- [x] Mongoose
